title:  "JNEL.ME"
tagline: "Jeremy Nelson | Data Analytics | Chicago, IL"
description:

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'millennial-3'

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Leisure', folder: 'pages', file: 'travel-leisure.html'}
- {name: 'Digital', folder: 'pages', file: 'digital.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/jerednel'}
- {icon: 'facebook', link: 'https://www.facebook.com/jeremy.nels'}
- {icon: 'instagram', link: 'https://instagram.com/jerednel'}
- {icon: 'envelope', link: 'mailto:jerednel@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
